import './globals.css';
import type { Metadata } from 'next';
import { IBM_Plex_Mono } from 'next/font/google';

const ibmFont = IBM_Plex_Mono({ subsets: ['latin'], weight: '500' });

export const metadata: Metadata = {
  title: 'UI Challange',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={ibmFont.className}>{children}</body>
    </html>
  );
}
